### PR TITLE
Add takeWhileM

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by michaelt** [comment]
Oh cool. You should export it though.

**Comment by mitchellwrosen** [comment]
If you insist :)

**Comment by mitchellwrosen** [comment]
Oops, in exporting it I accidentally included all of the trailing whitespace changes that my editor applies automatically. Let me know if I should revert that.

**Comment by michaelt** [comment]
Thanks! Sorry to be losing my precious whitespace. I should probably get a more rational editor.

**Pull request merged**
